/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;


import leetcode.LongestValidParentheses.Solution;

public class App {

    public static void main(String[] args) {
        Solution s = new Solution();

        System.out.println(s.longestValidParentheses(")()())"));
    }
}
