/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import leetcode.LongestSubstringWithoutRepeatingCharacters.Solution;

public class App {

    public static void main(String[] args) {
        Solution sol = new Solution();
        String s = "abcabcbb";
        System.out.println(sol.lengthOfLongestSubstring(s));
    }
}
